name: "Distribution"

on:
  workflow_dispatch:
  schedule:
    - cron: "0 */6 * * *" # Every 6h

env:
  MORALIS_API_KEY: ${{ secrets.MORALIS_API_KEY }}

jobs:
  run-operation:
    runs-on: ubuntu-latest
    permissions:
      # Give the default GITHUB_TOKEN write permission to commit and push the
      # added or changed files to the repository.
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GIT_ACCESS_TOKEN }}
          fetch-depth: 0
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10.13"

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "20.5.1"

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 9.12.3

      - name: Install dependencies
        run: pnpm install --no-frozen-lockfile

      - name: Run merkle generation
        run: make -f automation/distribution.mk run-merkle
        env:
          EXPLORER_KEY: ${{ secrets.ETHERSCAN_TOKEN }}
          WEB3_ALCHEMY_API_KEY: ${{ secrets.WEB3_ALCHEMY_API_KEY}}

      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_user_name: GitHub Action Bot
          commit_user_email: action@github.com
          commit_author: GitHub Action Bot <action@github.com>
      
      - name: Clean up
        if: always()
        run: make -f automation/distribution.mk clean
  
  trigger-set-root:
    needs: run-operation
    runs-on: ubuntu-latest
    if: ${{ github.event.inputs.mode == 'execute' }} && success()
    steps:
      - name: Trigger set root
        if: ${{ github.event.inputs.mode == 'execute' }}
        uses: peter-evans/repository-dispatch@v3
        with:
          token: ${{ secrets.GIT_ACCESS_TOKEN }}
          repository: stake-dao/workflows
          event-type: hook-incentive-set-root